version: '3'
services:
  web:
    container_name: topology-web-container
    build: .
#    command: bundle exec ruby config.ru -o 0.0.0.0
    command: bundle exec rackup config.ru -p 4567 -o 0.0.0.0
    ports:
      - 4567:4567
    volumes:
      - .:/usr/src/test
